spring.application.name=threatintel-lite
spring.datasource.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
